{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventium.redisHost" . }}
  labels:
    {{- include "eventium.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "eventium.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eventium.redisHost" . }}
  labels:
    {{- include "eventium.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "eventium.redisHost" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "eventium.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "eventium.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
        fsGroup: 999
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["redis-server", "--save", "60", "1", "--appendonly", "no"]
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
{{- end }}
