apiVersion: v2
name: eventium
description: Plugin tabanlı olay izleme ve bildirim dashboard platformu (tek image)
type: application
version: 0.1.1
appVersion: "latest"
home: https://github.com/cosarberk/eventium
sources:
  - https://github.com/cosarberk/eventium
maintainers:
  - name: cosarberk
